
# common commands


all:
# display with raw acceleration data with normal fft PSD and directional spectral
	.\cdip_driver.py --raw --norm --ds ".\067.20201225_1200.20201225_1600.nc"


banding:
# display with raw acceleration data with banding fft PSD and directional spectral
	.\cdip_driver.py --raw --banding --ds ".\067.20201225_1200.20201225_1600.nc"
	

welch:	
# display with raw acceleration data with welch windows fft PSD and directional spectral
	.\cdip_driver.py --raw --welch --ds ".\067.20201225_1200.20201225_1600.nc"